# Generated by Django 5.0.6 on 2024-06-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrar_serie_pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_serie', models.CharField(max_length=120, verbose_name='Titulo Serie')),
                ('fecha_serie', models.DateTimeField(verbose_name='Fecha Serie')),
                ('temporadas', models.IntegerField(verbose_name='Nº Temporadas')),
                ('episodios', models.IntegerField(verbose_name='Nº Episodios')),
                ('plataforma', models.CharField(max_length=120, verbose_name='Plataforma Serie')),
                ('description', models.TextField(blank=True, verbose_name='Description Serie')),
                ('genero', models.CharField(max_length=120, verbose_name='Género Serie')),
                ('puntuacion', models.IntegerField(verbose_name='Puntuacion Serie')),
                ('finalizada', models.BooleanField(default=False, verbose_name='Finalizada?')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios Serie')),
                ('serie_pelicula_imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('serie_o_pelicula', models.CharField(max_length=120, verbose_name='Serie/Pelicula')),
                ('recomendado_por', models.CharField(max_length=120, verbose_name='Recomendado Por')),
            ],
        ),
    ]
