# Generated by Django 5.0.6 on 2024-06-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series_peliculas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar_serie_pelicula',
            name='episodios',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº Episodios'),
        ),
        migrations.AlterField(
            model_name='registrar_serie_pelicula',
            name='temporadas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº Temporadas'),
        ),
    ]
