# Generated by Django 5.0.6 on 2024-06-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series_peliculas_app', '0002_alter_registrar_serie_pelicula_episodios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar_serie_pelicula',
            name='fecha_serie',
            field=models.DateField(verbose_name='Fecha Serie'),
        ),
    ]
